### ISSUE TITLE
Upgrade to 1.0

### ISSUE THREAD

**Issue by jorgebucaran** [lukejacksonn/hyperapp-pwa#4]
Just a friendly reminder that [Hyperapp 1.0](https://hackernoon.com/introducing-hyperapp-1-0-dbf4229abfef) has officially hit the streets and this module is now using an older API. Time to upgrade! 👋 

See also: https://github.com/hyperapp/awesome/issues/18

**Comment by lukejacksonn** [comment]
Thanks. Done https://github.com/lukejacksonn/hyperapp-pwa/commit/95ef3bd8c1db57e70529a6eeea396b3460f4de3b :tada:
